DELETE FROM CITIES;
ALTER TABLE CITIES MODIFY CITY_ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

-- table OPENING_HOURS
INSERT INTO opening_hours VALUES (1, '08-20', '08-20', '08-20', '08-20', '08-20', null, null);
INSERT INTO opening_hours VALUES (2, '08-22', '08-22', '08-22', '08-20', '09-12', null, null);
INSERT INTO opening_hours VALUES (3, '08-20', '08-22', null, '08-20', '09-12', '10-12', '10-12');
commit;

-- table CITIES
INSERT INTO cities VALUES (1, 'Warsaw');
INSERT INTO cities VALUES (2, 'Lodz');
INSERT INTO cities VALUES (3, 'Gdansk');
INSERT INTO cities VALUES (4, 'Wroclaw');
INSERT INTO cities VALUES (5, 'Krakow');
commit;

-- table ADDRESSES
INSERT INTO addresses VALUES (1, 'Marszalkowska', 24, 1);
INSERT INTO addresses VALUES (2, 'Prosta', 4, 1);
INSERT INTO addresses VALUES (3, 'Koszykowa', 18, 1);
INSERT INTO addresses VALUES (4, 'Okopowa', 28, 3);
INSERT INTO addresses VALUES (5, 'Jasna', 273, 3);
INSERT INTO addresses VALUES (6, 'Jasna', 283, 3);
INSERT INTO addresses VALUES (7, 'Majowa', 2, 2);
INSERT INTO addresses VALUES (8, 'Kwiatowa', 3, 2);
INSERT INTO addresses VALUES (9, 'Chmielna', 73, 4);
INSERT INTO addresses VALUES (10, 'Zelazna', 31, 5);
INSERT INTO addresses VALUES (11, 'Szczesliwa', 27, 3);
INSERT INTO addresses VALUES (12, 'Prosta', 5, 1);
INSERT INTO addresses VALUES (13, 'Prosta', 6, 1);
INSERT INTO addresses VALUES (14, 'Zwirowa', 46, 1);
INSERT INTO addresses VALUES (15, 'Polna', 77, 1);
INSERT INTO addresses VALUES (16, 'Brukowa', 68, 2);
commit;

-- table ACCOUNT_TYPES
INSERT INTO account_types VALUES (1, 'personal');
INSERT INTO account_types VALUES (2, 'savings');
INSERT INTO account_types VALUES (3, 'company');
INSERT INTO account_types VALUES (4, 'recur_deposit');
INSERT INTO account_types VALUES (5, 'fixed_deposit');
INSERT INTO account_types VALUES (6, 'salary');
INSERT INTO account_types VALUES (7, 'student');
INSERT INTO account_types VALUES (8, 'senior');
commit;

-- table CARD_TYPES
INSERT INTO card_types VALUES (1, 'credit');
INSERT INTO card_types VALUES (2, 'debit');
INSERT INTO card_types VALUES (3, 'savings');
INSERT INTO card_types VALUES (4, 'student');
commit;

-- table TRANSACTION_TYPE
INSERT INTO transaction_type VALUES (1, 'withdrawal');
INSERT INTO transaction_type VALUES (2, 'payment');
INSERT INTO transaction_type VALUES (3, 'return');
INSERT INTO transaction_type VALUES (4, 'transfer_in');
INSERT INTO transaction_type VALUES (5, 'transfer_out');
commit;

-- table PROFESSIONS
INSERT INTO professions VALUES (1, 'clerk', 3000, 9000);
INSERT INTO professions VALUES (2, 'accountant', 2000, 7000);
INSERT INTO professions VALUES (3, 'programmer', 10000, 20000);
INSERT INTO professions VALUES (4, 'assistant', 3200, 7200);
INSERT INTO professions VALUES (5, 'cleaner', 1500, 3000);
INSERT INTO professions VALUES (6, 'banker', 5500, 9000);
INSERT INTO professions VALUES (7, 'analyst', 7500, 12000);
INSERT INTO professions VALUES (8, 'manager', 15000, 30000);
commit;

-- table PERSONAL DATA
INSERT INTO personal_data VALUES (1, 'Beata', 'Jablonska', '46548379354', '486756114', '6bedce9bbf0230f0bd030d7fb646e51b', 2);
INSERT INTO personal_data VALUES (2, 'Bartosz', 'Nowak', '05148377354', '487756971', '5b706a286a4dd856eed4c1da00621892', 2);
INSERT INTO personal_data VALUES (3, 'Anna', 'Kowalska', '00148671354', '223756877', '4997f1bfb16fb9704366c2230700c5f1', 3);
INSERT INTO personal_data VALUES (4, 'Celina', 'Makowska', '70345671354', '175756877', '80dabd6f7ef57febfb984b567694cb91', 6);
INSERT INTO personal_data VALUES (5, 'Darek', 'Malinowski', '70345678897', '225346877', '681e6dcd6cc95afd236931f5480cc437', 5);
INSERT INTO personal_data VALUES (6, 'Daria', 'Malinowska', '70145623297', '708346247', 'c540c89a0488c332f2de7e7e6d5c22ca', 5);
INSERT INTO personal_data VALUES (7, 'Ewelina', 'Kasprzak', '24335623497', '900346247', '4762c4f5f5df5ed4e0d5acb548b07e4b', 1);
INSERT INTO personal_data VALUES (8, 'Eryk', 'Konieczny', '70115623465', '717566247', 'cef3df575a7ae9b017d448b34947af04', 7);
commit;

-- table EMPLOYEES
INSERT INTO employees VALUES (1, 4500, 4, 2);
INSERT INTO employees VALUES (2, 5700, 4, 6);
commit;

-- table CLIENTS
INSERT INTO clients VALUES (1, 1, 1);
INSERT INTO clients VALUES (2, 3, 2);
INSERT INTO clients VALUES (3, 4, 1);
INSERT INTO clients VALUES (4, 5, 1);
INSERT INTO clients VALUES (5, 7, 2);
INSERT INTO clients VALUES (6, 8, 1);
commit;

-- table BANK_BRANCHES
INSERT INTO bank_branches VALUES (1, 2, 1, 2);
INSERT INTO bank_branches VALUES (2, 2, 2, 1);
INSERT INTO bank_branches VALUES (3, 1, 3, 3);
commit;

-- table BANK_ACCOUNTS
INSERT INTO bank_accounts VALUES (1, 20000, 1, TO_DATE('06-08-2000', 'DD-MM-YYYY'), null, 3, null, null, 6, 1);
INSERT INTO bank_accounts VALUES (2, 80000, 2, TO_DATE('06-02-1980', 'DD-MM-YYYY'), TO_DATE('06-02-2022', 'DD-MM-YYYY'), 4, null, null, 2, 1);
INSERT INTO bank_accounts VALUES (3, 15600, 1, TO_DATE('09-05-2009', 'DD-MM-YYYY'), null, 2, null, null, 1, 2);
commit;

-- table CARDS
INSERT INTO cards VALUES (1, TO_DATE('06-06-2023', 'DD-MM-YYYY'), 'hash', 'hash', 1, 1);
INSERT INTO cards VALUES (2, TO_DATE('01-01-2023', 'DD-MM-YYYY'), 'hash', 'hash', 2, 1);
INSERT INTO cards VALUES (3, TO_DATE('11-12-2023', 'DD-MM-YYYY'), 'hash', 'hash', 2, 3);
commit;

-- table TRANSACTION_HISTORY
INSERT INTO transaction_history VALUES (1, 20, TO_DATE('06-06-2021', 'DD-MM-YYYY'), 1, 2);
INSERT INTO transaction_history VALUES (2, 200, TO_DATE('07-06-2021', 'DD-MM-YYYY'), 1, 2);
INSERT INTO transaction_history VALUES (3, 50, TO_DATE('07-06-2021', 'DD-MM-YYYY'), 1, 1);
INSERT INTO transaction_history VALUES (4, 64, TO_DATE('09-06-2021', 'DD-MM-YYYY'), 1, 2);
INSERT INTO transaction_history VALUES (5, 670, TO_DATE('16-06-2021', 'DD-MM-YYYY'), 1, 2);
commit;

UPDATE employees SET branch_id=1 WHERE employee_id=1;
UPDATE employees SET branch_id=3 WHERE employee_id=2;
commit;
